server:
  port:

spring:
  datasource:
    url:
    driverClassName:
    initialization-mode:
    continue-on-error:

  jpa:
    hibernate:
      ddl-auto:
      show-sql:
    database-platform:
    properties:
      hibernate:
        format_sql:
  data:
    jpa:
      repositories:
        enabled:

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
          connectiontimeout:
          timeout:
          writetimeout: 
